// <auto-generated />
using CustomDatabase2.ShardingDataInDb.ShardingDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomDatabase2.ShardingDataInDb.ShardingDb.Migrations
{
    [DbContext(typeof(ShardingDataDbContext))]
    partial class ShardingDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("AuthPermissions.AspNetCore.ShardingServices.DatabaseInformation", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ShardingData");

                    b.HasData(
                        new
                        {
                            Name = "Default Database",
                            ConnectionName = "DefaultConnection",
                            DatabaseType = "Sqlite"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
